# Generated by Django 3.2.5 on 2021-10-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userType',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('REGULAR', 'Regular')], default='ADMIN', max_length=10),
        ),
    ]
