# Generated by Django 3.2.5 on 2021-10-04 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='user_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='regular',
            old_name='user_id',
            new_name='id',
        ),
    ]
