# Generated by Django 3.2.5 on 2021-10-04 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211004_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='admin_user', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
